
services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homiehq-frontend
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5008/api
    networks:
      - homiehq-network
    depends_on:
      - web
  # Backend Service - Using the exact configuration you provided
  web:
    image: harung43/homiehq:backend
    container_name: homiehq-backend
    ports:
      - "5008:5008"
    volumes:
      - ./uploads:/app/uploads  # Only mount uploads directory
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://homiehq:homiehq@db:5432/homiehq
      - SQLALCHEMY_DATABASE_URI=postgresql://homiehq:homiehq@db:5432/homiehq
      - DATABASE_HOST=db
      - POSTGRES_USER=homiehq
      - POSTGRES_PASSWORD=homiehq
      - POSTGRES_DB=homiehq
      - CORS_ALLOWED_ORIGINS=http://localhost:3002,http://frontend:3000
    depends_on:
      - db
    networks:
      - homiehq-network

  # Database Service - Using the exact configuration you provided
  db:
    image: postgres:13
    container_name: homiehq-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=homiehq
      - POSTGRES_PASSWORD=homiehq
      - POSTGRES_DB=homiehq
    ports:
      - "5432:5432"
    networks:
      - homiehq-network

volumes:
  postgres_data:

networks:
  homiehq-network:
    driver: bridge